services:
  app:
    build:
      target: dev
    ports:
      - 8050:8050
    environment:
      PGHOST: postgres
      PGDATABASE: app
      PGUSER: postgres
      PGPASSWORD: postgres
    develop:
      watch:
        - path: app.py
          action: sync
          target: /usr/local/app/app.py
    

  postgres:
    image: postgres:17.5
    # ports:
    #   - "5432:5432"
    volumes:
      - ./data-import:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app

  pgadmin:
    image: dpage/pgadmin4:9.3.0
    ports:
      - "8080:80"
    volumes:
      - ./dev/pgadmin/servers.json:/pgadmin4/servers.json
      - ./dev/pgadmin/pgpass:/config/pgpass
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@mycomp.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    depends_on:
      - postgres
    post_start:
      - command: chmod 600 /config/pgpass